### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by noran97** [AbdelrahmanBadr22/G1_8bit_MCUs_Drivers#47]
an error appears in pull request #43  when adding config.h in source file which is "undeclared variables" while if we add it to the header file then it will be resolved.
 
![photo_5954028668009430212_y](https://github.com/AbdelrahmanBadr22/G1_8bit_MCUs_Drivers/assets/99215076/c3fced52-7a6f-475d-8ff7-3f7a44d0f5b3)

**Comment by AbdelrahmanBadr22** [comment]
Hi @noran97 <br>
This error is caused because you didn't include the file in the right order in the main function. Remember order of including files matters also `hal/Keypad/Keypad.h` need `#include "hal/Keypad/Config.h" as the defined macro is in second one so we have to consider the dependency and if want to use keypad driver we have to include both files : 
```
#include "hal/Keypad/Config.h"
#include "hal/Keypad/Keypad.h"
```
I made a commit i.e. 95454573c847d57ab9308c426fe51f02959d5e08 with changes to show you what I mean also for main.c it's look like your local branch not updated as Its appears like : 
![image](https://github.com/AbdelrahmanBadr22/G1_8bit_MCUs_Drivers/assets/60186885/5e4b7927-d79e-442a-a633-c1c715e5cf35)

Remember for each test we have a main so make sure your are changing the real `main.c` 
I am going to close this issue and if you still has a problem reopen
